# http://docs.travis-ci.com/user/languages/objective-c/
# https://github.com/facebook/xctool

language: objective-c

osx_image: xcode7

xcode_project: SwiftExpression/SwiftExpression.xcodeproj
xcode_scheme: SwiftExpression
xcode_sdk: iphonesimulator9.0

script:
  xctool
  -project SwiftExpression/SwiftExpression.xcodeproj
  -scheme SwiftExpression
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
